Repository Digiratory/StatTools, pull requests merged in 2025-04, with the labels that each got.

#16 15 value from outside the generator
  CHANGELOG.md
  StatTools/generators/lbfbm_generator.py
  research/data_recovery.ipynb
  tests/test_lbfbm_generator.py
Labels: bug, enhancement

#17 12 bug changelogmd contains a violation of markdown
  CHANGELOG.md
  README.md
Labels: bug, documentation

#29 25 dfa for nonequidistant time series
  CHANGELOG.md
  StatTools/analysis/nonequidistant/__init__.py
  StatTools/analysis/nonequidistant/dfa.py
  pyproject.toml
  tests/test_ne_dfa.py
Labels: enhancement

#30 repo: Exclude Jupyter Notebooks from GitHub Programming Language Stats
  .gitattributes
Labels: documentation, enhancement

#31 Kalman filter
  CHANGELOG.md
  StatTools/filters/kalman_filter.py
  StatTools/generators/kasdin_generator.py
  requirements.txt
  research/data_recovery.ipynb
  research/kalman_filter.ipynb
  setup.py
Labels: enhancement

#32 style: apply pre-commit hooks for all files
  .github/workflows/test-and-release.yml
  DFA.cpp
  StatTools/Gamma.py
  StatTools/analysis/__init__.py
  StatTools/analysis/dfa.py
  StatTools/analysis/dpcca.py
  StatTools/analysis/dpcca_as_class.py
  StatTools/analysis/fa.py
  StatTools/analysis/movmean.py
  StatTools/analysis/qss.py
  StatTools/auxiliary.py
  StatTools/generators/__init__.py
  StatTools/generators/base_filter.py
  StatTools/generators/cholesky_transform.py
  StatTools/generators/fbm.py
  StatTools/generators/field_generator.py
  StatTools_C_API.cpp
  setup.py
  tests/test_dfa.py
  tests/test_dpcca.py
  tests/test_fa.py
  tests_manual/cholesky_with_R.py
  tests_manual/dfa_test.py
  tests_manual/dpcca_pipe.py
  tests_manual/dpcca_test.py
  tests_manual/test_buffer.py
Labels: enhancement

#33 13 linter warning
  CHANGELOG.md
  StatTools/analysis/dpcca.py
Labels: bug, documentation

#35 style: add saving and increase font size
  .gitignore
  research/kalman_filter.ipynb
Labels: enhancement
